README.md
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html#using-iam-capabilities
=> Fix CLI command to include capabilities ack

README.md
=> Remove actual account id

cloudformation/jupiterone-cloudformation.json
User will be provided the account id in J1. Missed this in #11 😬
=> Remove default account id

README.md
Add new macie permissions from the cloudformation .json file to the readme
=> Add macie permissions to readme

README.md
=> INT-1025 - Update CloudTrail documentation with the entities and relationships it updates

README.md, cloudformation/events-cloudformation.json
=> add autoscaling event rules

README.md
Update README.md with Redshift Serverless Permissions:
```
"redshift-serverless:ListUsageLimits",
"redshift-serverless:ListNamespaces",
"redshift-serverless:ListWorkgroups",
```
=> Update README.md with Redshift Serverless Permissions

cloudformation/events-cloudformation.json
Adds an IAM role to the CloudTrail stack
This role gets added as a target to the event rule
=> Add IAM Role to CloudTrail stack

README.md, cloudformation/events/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation/cloudformation-template.json
=> [Github Action] - Update Documentation v1.113.2

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md
=> [Github Action] - Update Documentation v1.121.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.127.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/cloudformation-template.json, cloudformation/iam-cloudformation/managed-policy.md, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.133.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.140.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.143.1

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.156.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.157.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/cloudformation-template.json, cloudformation/iam-cloudformation/managed-policy.md, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.158.0

README.md, cloudformation/events/cloudformation-template.json
INT-7634 INT-7635 INT-7636 INT-7637 INT-7638
=> Add RDS DB Instance Events

README.md
=> [Github Action] - Update Documentation v1.176.1

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.181.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.182.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.184.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.189.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.207.1

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.223.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.229.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.231.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/cloudformation-template.json, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.235.1

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.244.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.273.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.286.1

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/cloudformation-template.json, cloudformation/iam-cloudformation/managed-policy.md, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.288.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.293.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.295.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.296.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.299.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.316.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.317.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.319.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf, cloudformation/iam-cloudformation/cloudformation-template.json, cloudformation/iam-cloudformation/managed-policy.md, cloudformation/iam-cloudformation/terraform.tf
=> [Github Action] - Update Documentation v1.324.0

cloudformation/iam-cloudformation-detailed/cloudformation-template.json, cloudformation/iam-cloudformation-detailed/managed-policy.md, cloudformation/iam-cloudformation-detailed/terraform.tf
=> [Github Action] - Update Documentation v1.329.0
